export const BUTTON_TEXTS: { [key: string]: { [lang: string]: string } } = {
  lecture: {
    'English - US & Canada': "Welcome to the AI E-Learning Course! Gain core AI skills through interactive lessons and projects in machine learning. Perfect for beginners and those seeking deeper knowledge. Enjoy learning!",
    'French - France': "Bienvenue dans le cours d'apprentissage en ligne sur l'IA ! Acquérez des compétences clés en IA grâce à des leçons interactives et des projets en apprentissage automatique. Parfait pour les débutants et ceux qui souhaitent approfondir leurs connaissances. Bon apprentissage !",
    'German - Germany': "Willkommen beim KI-E-Learning-Kurs! Erwerben Sie grundlegende KI-Fähigkeiten durch interaktive Lektionen und Projekte im maschinellen Lernen. Perfekt für Anfänger und alle, die ihr Wissen vertiefen möchten. Viel Spaß beim Lernen!",
    'Spanish - Spain': "¡Bienvenido al curso de aprendizaje en línea sobre IA! Adquira habilidades fundamentales en inteligencia artificial a través de lecciones interactivas y proyectos de aprendizaje automático. Perfecto para principiantes y quienes buscan profundizar sus conocimientos. ¡Disfruta aprendiendo!",
    'Spanish - Mexico': "¡Bienvenido al curso de aprendizaje en línea sobre IA! Adquira habilidades fundamentales en inteligencia artificial a través de lecciones interactivas y proyectos de aprendizaje automático. Perfecto para principiantes y quienes buscan profundizar sus conocimientos. ¡Disfruta aprendiendo!",
    'Italian - Italy': "Benvenuto al corso di e-learning sull'intelligenza artificiale! Acquisisci competenze fondamentali in IA attraverso lezioni interattive e progetti di machine learning. Perfetto per principianti e per chi desidera approfondire le proprie conoscenze. Buono studio!",
    'Portuguese - Brazil': "Bem-vindo ao Curso de E-Learning em IA! Adquira habilidades essenciais em inteligência artificial com aulas interativas e projetos em aprendizado de máquina. Perfeito para iniciantes e para quem deseja aprofundar o conhecimento. Aproveite o aprendizado!",
    'Chinese - China': "欢迎参加人工智能在线学习课程！通过互动课程和机器学习项目掌握核心人工智能技能。非常适合初学者和希望深入了解的人。祝您学习愉快！",
    'Dutch - Netherlands': "Welkom bij de AI E-Learning Cursus! Verwerf kernvaardigheden in kunstmatige intelligentie via interactieve lessen en machine learning-projecten. Perfect voor beginners en voor wie dieper inzicht wil krijgen. Veel leerplezier!",
    'Japanese - Japan': "AI eラーニングコースへようこそ！インタラクティブなレッスンと機械学習プロジェクトを通じて、AIの基本スキルを習得しましょう。初心者や、より深い知識を求める方に最適です。学習をお楽しみください！",
    'Hindi - India': "एआई ई-लर्निंग कोर्स में आपका स्वागत है! इंटरैक्टिव पाठों और मशीन लर्निंग प्रोजेक्ट्स के माध्यम से एआई की मूलभूत स्किल्स सीखें। यह शुरुआती और गहराई से ज्ञान प्राप्त करने वालों के लिए उपयुक्त है। सीखने का आनंद लें!",
    'Korean - Korea': "AI e-러닝 과정에 오신 것을 환영합니다! 대화형 수업과 머신러닝 프로젝트를 통해 핵심 AI 기술을 습득하세요. 초보자 및 더 깊은 지식을 원하는 분들에게 적합합니다. 즐겁게 학습하세요!",
    'Tamil - India': "AI இ-லெர்னிங் பாடநெறிக்கு வரவேற்கிறோம்! இயந்திர கற்றல் திட்டங்களுடனும், ஊடாடும் பாடங்களுடனும் மூலம் முக்கியமான AI திறன்களைப் பெறுங்கள். துவக்க நிலையிலிருப்பவர்களுக்கும், ஆழமான அறிவை நாடுவோருக்கும் இதுவே சிறந்தது. மகிழ்ச்சியாகக் கற்குங்கள்!",
    'Bengali - India': "AI ই-লার্নিং কোর্সে আপনাকে স্বাগতম! ইন্টারঅ্যাকটিভ পাঠ ও মেশিন লার্নিং প্রজেক্টের মাধ্যমে মূল AI দক্ষতা অর্জন করুন। নতুনদের ও যারা আরও গভীর জ্ঞান চান তাদের জন্য উপযুক্ত। শেখার আনন্দ উপভোগ করুন!",
    'Polish - Poland': "Witamy na kursie e-learningowym z zakresu sztucznej inteligencji! Zdobądź podstawowe umiejętności z AI dzięki interaktywnym lekcjom i projektom z uczenia maszynowego. Idealne dla początkujących oraz osób chcących pogłębić swoją wiedzę. Miłej nauki!",
    'Slovak - Slovakia': "Vitajte v online kurze o umelej inteligencii! Získajte základné zručnosti v oblasti AI pomocou interaktívnych lekcií a projektov strojového učenia. Ideálne pre začiatočníkov aj tých, ktorí chcú prehĺbiť svoje vedomosti. Prajeme príjemné učenie!",
    'Croatian - Croatia': "Dobrodošli na AI e-učenje! Steknite osnovne vještine umjetne inteligencije kroz interaktivne lekcije i projekte iz strojnog učenja. Savršeno za početnike i one koji žele produbiti svoje znanje. Uživajte u učenju!",
    'Greek - Greece': "Καλώς ήρθατε στο μάθημα εξ αποστάσεως εκπαίδευσης για την Τεχνητή Νοημοσύνη! Αποκτήστε βασικές δεξιότητες AI μέσα από διαδραστικά μαθήματα και έργα μηχανικής μάθησης. Ιδανικό για αρχάριους και για όσους επιθυμούν βαθύτερη γνώση. Καλή μάθηση!",
  },
  story: {
    'English - US & Canada': "The Azure Starling, a vibrant new bird species. Known for its striking blue feathers and melodic song, it thrives in tropical forests. Discover its unique behaviors and habitat today!",
    'French - France': "Le Azure Starling, une nouvelle espèce d'oiseau éclatante. Connu pour ses plumes bleues éclatantes et son chant mélodieux, il prospère dans les forêts tropicales. Découvrez dès aujourd’hui ses comportements uniques et son habitat !",
    'German - Germany': "Der Azure Starling – eine lebhafte neue Vogelart. Bekannt für sein auffälliges blaues Gefieder und seinen melodischen Gesang, gedeiht er in tropischen Wäldern. Entdecken Sie heute sein einzigartiges Verhalten und seinen Lebensraum!",
    'Spanish - Spain': "El Estornino Azul, una nueva especie de ave vibrante. Conocido por sus llamativas plumas azules y su canto melódico, prospera en los bosques tropicales. ¡Descubre hoy sus comportamientos únicos y su hábitat!",
    'Spanish - Mexico': "El Estornino Azul, una nueva especie de ave vibrante. Conocido por sus llamativas plumas azules y su canto melódico, prospera en los bosques tropicales. ¡Descubre hoy sus comportamientos únicos y su hábitat!",
    'Italian - Italy': "Lo Storno Azzurro, una nuova specie di uccello vivace. Conosciuto per il suo piumaggio blu brillante e il canto melodico, prospera nelle foreste tropicali. Scopri oggi i suoi comportamenti unici e il suo habitat!",
    'Portuguese - Brazil': "O Estorninho Azul, uma nova e vibrante espécie de ave. Conhecido por suas penas azuis marcantes e canto melódico, prospera em florestas tropicais. Descubra hoje seus comportamentos únicos e habitat!",
    'Chinese - China': "蓝星椋鸟是一种充满活力的新鸟类物种。它以鲜艳的蓝色羽毛和悦耳的歌声而闻名，生活在热带森林中。今天就来探索它独特的行为和栖息地吧！",
    'Dutch - Netherlands': "De Azure Spreeuw, een levendige nieuwe vogelsoort. Bekend om zijn opvallende blauwe veren en melodieuze zang, gedijt hij in tropische bossen. Ontdek vandaag nog zijn unieke gedrag en leefgebied!",
    'Japanese - Japan': "アズール・スターリングは、鮮やかな新種の鳥です。鮮やかな青い羽と美しいさえずりで知られ、熱帯雨林で生息しています。今日、そのユニークな行動や生息地を発見してみましょう！",
    'Hindi - India': "एज़्योर स्टार्लिंग, एक नई और जीवंत पक्षी प्रजाति है। इसकी चमकदार नीली पंख और मधुर आवाज के लिए यह जाना जाता है, और यह उष्णकटिबंधीय वनों में फलता-फूलता है। आज ही इसके अनोखे व्यवहार और आवास की खोज करें!",
    'Korean - Korea': "아주르 스타링은 생동감 넘치는 새로운 조류 종입니다. 선명한 파란 깃털과 감미로운 노래로 잘 알려져 있으며, 열대 우림에서 번성합니다. 지금 그 독특한 행동과 서식지를 알아보세요!",
    'Tamil - India': "அசூர் ஸ்டார்லிங் என்பது ஒரு புத்தம் புதிய உற்சாகமான பறவை இனமாகும். அதன் திகழும் நீல இறகுகளுக்கும் இனிமையான பாடலுக்கும் பெயர் பெற்றது. இது சூடான காடுகளில் வளம் பெறுகிறது. இன்று அதன் தனித்துவமான நடத்தையும் வாழ்விடத்தையும் கண்டறியுங்கள்!",
    'Bengali - India': "অ্যাজুর স্টারলিং, একটি উজ্জ্বল নতুন পাখির প্রজাতি। এর উজ্জ্বল নীল পালক এবং সুরেলা গান এর পরিচয়, যা ক্রান্তীয় অরণ্যে বসবাস করে। আজই এর অনন্য আচরণ এবং বাসস্থান আবিষ্কার করুন!",
    'Polish - Poland': "Azure Starling – nowy, żywiołowy gatunek ptaka. Znany ze swoich intensywnie niebieskich piór i melodyjnego śpiewu, żyje w lasach tropikalnych. Odkryj dziś jego unikalne zachowania i środowisko życia!",
    'Slovak - Slovakia': "Azure Starling je živý nový druh vtáka. Známy svojím nápadným modrým perím a melodickým spevom, darí sa mu v tropických lesoch. Objavte dnes jeho jedinečné správanie a prostredie!",
    'Croatian - Croatia': "Azure Starling je nova, živopisna vrsta ptice. Poznata po svojim upečatljivim plavim perima i melodičnom pjevu, uspijeva u tropskim šumama. Otkrijte njezino jedinstveno ponašanje i stanište već danas!",
    'Greek - Greece': "Το Azure Starling, ένα ζωντανό νέο είδος πτηνού. Γνωστό για τα εντυπωσιακά μπλε φτερά του και το μελωδικό του τραγούδι, ευδοκιμεί στα τροπικά δάση. Ανακαλύψτε σήμερα τις μοναδικές του συμπεριφορές και το φυσικό του περιβάλλον!",
  },
  advertisement: {
    'English - US & Canada': "Transform your mornings with our Smart Coffee Maker. Brew the perfect cup with ease. Set your preferences and wake up to fresh coffee every day. Order now for a smarter start!",
    'French - France': "Transformez vos matins avec notre cafetière intelligente. Préparez la tasse parfaite en toute simplicité. Définissez vos préférences et réveillez-vous chaque jour avec un café fraîchement préparé. Commandez maintenant pour un début de journée plus intelligent !",
    'German - Germany': "Verwandeln Sie Ihre Morgen mit unserer smarten Kaffeemaschine. Brühen Sie mühelos die perfekte Tasse. Stellen Sie Ihre Vorlieben ein und wachen Sie jeden Tag mit frischem Kaffee auf. Jetzt bestellen für einen klügeren Start in den Tag!",
    'Spanish - Spain': "Transforma tus mañanas con nuestra cafetera inteligente. Prepara la taza perfecta con facilidad. Configura tus preferencias y despierta cada día con café recién hecho. ¡Haz tu pedido ahora para un comienzo más inteligente!",
    'Spanish - Mexico': "Transforma tus mañanas con nuestra cafetera inteligente. Prepara la taza perfecta con facilidad. Configura tus preferencias y despierta cada día con café recién hecho. ¡Haz tu pedido ahora para un comienzo más inteligente!",
    'Italian - Italy': "Trasforma le tue mattine con la nostra macchina da caffè intelligente. Prepara la tazza perfetta con facilità. Imposta le tue preferenze e svegliati ogni giorno con caffè appena fatto. Ordina ora per un inizio di giornata più smart!",
    'Portuguese - Brazil': "Transforme suas manhãs com nossa Cafeteira Inteligente. Prepare a xícara perfeita com facilidade. Defina suas preferências e acorde todos os dias com um café fresquinho. Peça agora para um começo mais inteligente!",
    'Chinese - China': "用我们的智能咖啡机改变你的清晨。轻松冲泡完美咖啡。设置您的偏好，每天醒来都能享受新鲜咖啡。立即下单，开启更智能的一天！",
    'Dutch - Netherlands': "Transformeer je ochtenden met ons slimme koffiezetapparaat. Zet moeiteloos het perfecte kopje. Stel je voorkeuren in en word elke dag wakker met verse koffie. Bestel nu voor een slimme start!",
    'Japanese - Japan': "スマートコーヒーメーカーで朝の時間を変えましょう。簡単に完璧な一杯を淹れられます。お好みを設定すれば、毎朝新鮮なコーヒーの香りで目覚められます。今すぐ注文して、スマートな朝を始めましょう！",
    'Hindi - India': "हमारे स्मार्ट कॉफी मेकर के साथ अपनी सुबहों को बदलें। आसानी से परफेक्ट कप कॉफी बनाएं। अपनी पसंद सेट करें और हर सुबह ताज़ा कॉफी के साथ जागें। स्मार्ट शुरुआत के लिए अभी ऑर्डर करें!",
    'Korean - Korea': "스마트 커피 메이커로 아침을 바꿔보세요. 손쉽게 완벽한 커피 한 잔을 추출하세요. 취향을 설정하고 매일 아침 신선한 커피와 함께 일어나세요. 더 스마트한 시작을 위해 지금 주문하세요!",
    'Tamil - India': "எங்கள் ஸ்மார்ட் காபி மேக்கருடன் உங்கள் காலை நேரங்களை மாற்றிக் கொள்ளுங்கள். சுலபமாக சிறந்த காபி தயாரிக்கலாம். உங்கள் விருப்பங்களை அமைத்துக்கொண்டு, ஒவ்வொரு நாளும் புதிய காபியுடன் விழிக்கவும். புத்திசாலியான ஆரம்பத்திற்கு இப்போது ஆர்டர் செய்யுங்கள்!",
    'Bengali - India': "আমাদের স্মার্ট কফি মেকার দিয়ে আপনার সকালকে রূপান্তর করুন। সহজেই পারফেক্ট কফি তৈরি করুন। আপনার পছন্দ সেট করুন এবং প্রতিদিন সকালে তাজা কফি দিয়ে জাগুন। আরও স্মার্ট শুরু করতে এখনই অর্ডার করুন!",
    'Polish - Poland': "Odmień swoje poranki dzięki naszej inteligentnej kawiarce. Z łatwością zaparz idealną filiżankę. Ustaw swoje preferencje i budź się codziennie z zapachem świeżej kawy. Zamów teraz i rozpocznij dzień mądrzej!",
    'Slovak - Slovakia': "Premeňte svoje rána s naším inteligentným kávovarom. Jednoducho si pripravte dokonalú šálku kávy. Nastavte si svoje preferencie a každé ráno sa zobúdzajte s čerstvou kávou. Objednajte si teraz a začnite deň múdrejšie!",
    'Croatian - Croatia': "Transformirajte svoja jutra s našim pametnim aparatom za kavu. Lako skuhajte savršenu šalicu. Postavite svoje preferencije i budite se svakog dana uz svježu kavu. Naručite sada za pametniji početak dana!",
    'Greek - Greece': "Μεταμορφώστε τα πρωινά σας με τη Συσκευή Καφέ Smart. Ετοιμάστε το τέλειο φλιτζάνι με ευκολία. Ρυθμίστε τις προτιμήσεις σας και ξυπνήστε κάθε μέρα με φρέσκο καφέ. Παραγγείλτε τώρα για ένα πιο έξυπνο ξεκίνημα!",
  },
  podcast: {
    'English - US & Canada': "Welcome to 'AI Insights', your weekly update on the latest developments in artificial intelligence. From breakthroughs in machine learning to ethical AI, we cover it all. Stay tuned and stay informed!",
    'French - France': "Bienvenue dans « AI Insights », votre mise à jour hebdomadaire sur les dernières avancées en intelligence artificielle. Des percées en apprentissage automatique à l'IA éthique, nous couvrons tout. Restez à l'écoute et informé !",
    'German - Germany': "Willkommen bei „AI Insights“ – Ihrem wöchentlichen Update zu den neuesten Entwicklungen in der künstlichen Intelligenz. Von Durchbrüchen im maschinellen Lernen bis hin zu ethischer KI – wir berichten über alles. Bleiben Sie dran und informiert!",
    'Spanish - Spain': "Bienvenidos a 'AI Insights', tu actualización semanal sobre los últimos avances en inteligencia artificial. Desde innovaciones en aprendizaje automático hasta IA ética, lo cubrimos todo. ¡Sigue conectado e informado!",
    'Spanish - Mexico': "Bienvenidos a 'AI Insights', tu actualización semanal sobre los últimos avances en inteligencia artificial. Desde innovaciones en aprendizaje automático hasta IA ética, lo cubrimos todo. ¡Sigue conectado e informado!",
    'Italian - Italy': "Benvenuti a 'AI Insights', il tuo aggiornamento settimanale sulle ultime novità dell’intelligenza artificiale. Dalle scoperte nel machine learning all’IA etica, copriamo ogni aspetto. Resta sintonizzato e informato!",
    'Portuguese - Brazil': "Bem-vindo ao 'AI Insights', sua atualização semanal sobre as últimas novidades em inteligência artificial. De avanços em aprendizado de máquina à IA ética, cobrimos tudo. Fique ligado e bem informado!",
    'Chinese - China': "欢迎收听《AI 洞察》，为您带来每周人工智能领域的最新动态。从机器学习的突破到人工智能伦理问题，我们应有尽有。敬请关注，保持信息更新！",
    'Dutch - Netherlands': "Welkom bij 'AI Insights', jouw wekelijkse update over de nieuwste ontwikkelingen in kunstmatige intelligentie. Van doorbraken in machine learning tot ethische AI – wij behandelen het allemaal. Blijf luisteren en blijf op de hoogte!",
    'Japanese - Japan': "「AI Insights」へようこそ。人工知能の最新情報を毎週お届けします。機械学習のブレイクスルーから倫理的AIまで、あらゆる話題をカバー。ぜひご注目ください！",
    'Hindi - India': "AI Insights’ में आपका स्वागत है, यह आपका साप्ताहिक अपडेट है कृत्रिम बुद्धिमत्ता के नवीनतम विकास पर। मशीन लर्निंग की सफलताओं से लेकर नैतिक एआई तक, हम सब कुछ कवर करते हैं। जुड़े रहें और जानकारी में रहें!",
    'Korean - Korea': "AI Insights’에 오신 것을 환영합니다. 인공지능의 최신 동향을 매주 전해드립니다. 머신러닝의 돌파구부터 윤리적 AI까지 모든 내용을 다룹니다. 계속 청취하며 최신 정보를 받아보세요!",
    'Tamil - India': "AI Insights’ இற்குச் சமர்ப்பணம்! செயற்கை நுண்ணறிவின் புதிய வளர்ச்சிகளை வாரம் ஒருமுறை இங்கு அறியலாம். மெஷின் லெர்னிங் முன்னேற்றங்களிலிருந்து நெறிமுறை அடிப்படையிலான AI வரை அனைத்தையும் நாங்கள் உங்களுக்குத் தருகிறோம். தொடரவும், அறிவுடன் இருங்கள்!",
    'Bengali - India': "AI Insights’-এ আপনাকে স্বাগতম, এটি কৃত্রিম বুদ্ধিমত্তার সাম্প্রতিক অগ্রগতিগুলির সাপ্তাহিক আপডেট। মেশিন লার্নিংয়ের সাফল্য থেকে শুরু করে নৈতিক AI পর্যন্ত আমরা সব কিছুই কভার করি। সংযুক্ত থাকুন এবং তথ্যসমৃদ্ধ থাকুন!",
    'Polish - Poland': "Witamy w „AI Insights” – Twoim cotygodniowym przeglądzie najnowszych wydarzeń ze świata sztucznej inteligencji. Od przełomów w uczeniu maszynowym po etyczne AI – omawiamy wszystko. Bądź na bieżąco i dobrze poinformowany!",
    'Slovak - Slovakia': "Vitajte v „AI Insights“ – vašom týždennom prehľade najnovších udalostí v oblasti umelej inteligencie. Od prielomov v strojovom učení až po etickú AI – pokrývame všetko. Sledujte nás a zostaňte informovaní!",
    'Croatian - Croatia': "Dobrodošli u 'AI Insights', vaš tjedni pregled najnovijih dostignuća u području umjetne inteligencije. Od proboja u strojnom učenju do etičke AI – pokrivamo sve. Ostanite uz nas i budite informirani!",
    'Greek - Greece': "Καλώς ήρθατε στο 'AI Insights', την εβδομαδιαία σας ενημέρωση για τις τελευταίες εξελίξεις στην τεχνητή νοημοσύνη. Από τις καινοτομίες στη μηχανική μάθηση έως την ηθική ΤΝ, τα καλύπτουμε όλα. Μείνετε συντονισμένοι και ενημερωμένοι!",
  },
};
